platform :ios, '9.0'
use_frameworks!

target 'UbunGit_OC' do
  
  pod "RTRootNavigationController"
  pod 'NIMSDK'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  
  pod 'PPGetAddressBook'
  pod 'SuperPlayer'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Masonry'
  
  pod 'DoraemonKit/Core',  :configurations => ['Debug']
  pod 'DoraemonKit/WithLogger',  :configurations => ['Debug']
  pod 'DoraemonKit/WithLoad',  :configurations => ['Debug']
end
