platform :ios, '11.0'
use_frameworks!

target 'UbunGit_OC' do
  
  pod "RTRootNavigationController"
  pod 'NIMSDK'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'AFNetworking'
  
  pod 'PPGetAddressBook'

  pod 'SuperPlayerVC', :path => './Devpods/SuperPlayerVC/'
#

  pod 'DoraemonKit/Core',  :configurations => ['Debug']
  pod 'DoraemonKit/WithLogger',  :configurations => ['Debug']
  pod 'DoraemonKit/WithLoad',  :configurations => ['Debug']
  
  pod 'SuperPlayerVC', :path => './Devpods/SuperPlayerVC/'
  pod 'UGImagePickerController', :path => './Devpods/UGImagePickerController/'
#  pod 'UIMagic', :path => './UIMagic/'

  #  pod 'Mobileffmpeg', :path => './Devpods/Mobileffmpeg/'
end
